CREATE DATABASE IF NOT EXISTS personne;
USE personne;

CREATE TABLE UNITE (
    UNITCOD CHAR(4) PRIMARY KEY,
    UNITE CHAR(20),
    UMERE CHAR(4),
    BUDGET DECIMAL(12,2),
    FOREIGN KEY (UMERE) REFERENCES UNITE(UNITCOD)
);

CREATE TABLE QUALIF (
    CODQUAL CHAR(4) PRIMARY KEY,
    QUALIBEL CHAR(20)
);

CREATE TABLE EMPLOYE (
    EMPCOD CHAR(5) PRIMARY KEY,
    UNITCOD CHAR(4),
    NOM CHAR(20),
    JOBCODE CHAR(4),
    NIVEAU CHAR(4),
    TITRE CHAR(30),
    SEXE CHAR(1),
    DATNAISS DATETIME,
    QUALIFPR CHAR(4),
    SALAIRE DECIMAL(12,2),
    FOREIGN KEY (UNITCOD) REFERENCES UNITE(UNITCOD),
    FOREIGN KEY (QUALIFPR) REFERENCES QUALIF(CODQUAL)
);

CREATE TABLE EMPSQUAL (
    CODQUAL CHAR(4),
    EMPCOD CHAR(5),
    FOREIGN KEY (CODQUAL) REFERENCES QUALIF(CODQUAL),
    FOREIGN KEY (EMPCOD) REFERENCES EMPLOYE(EMPCOD)
);

CREATE TABLE POSTES (
    CODQUAL CHAR(4),
    UNITCOD CHAR(4),
    NOMBRE DECIMAL(4,2),
    BUDGETPOSTE DECIMAL(12,2),
    FOREIGN KEY (CODQUAL) REFERENCES QUALIF(CODQUAL),
    FOREIGN KEY (UNITCOD) REFERENCES UNITE(UNITCOD)
);
