use personne;
SELECT *
FROM EMPLOYE
WHERE EMPCOD IN (
    SELECT UMERE FROM UNITE WHERE UNITCOD IN ('2100', '2300')
);
-- 1
SELECT *
FROM EMPLOYE
WHERE TITRE ="RESPO"
AND (UNITCODE = '2100' OR UNITCODE = '2300');
-- 2
SELECT NOM, DATNAISS
FROM EMPLOYE
WHERE EMPCOD NOT IN (SELECT UMERE FROM UNITE WHERE UMERE IS NOT NULL)
  AND DATNAISS < '1940-01-01';
-- 3
SELECT NOM, TITRE
FROM EMPLOYE
WHERE NOM LIKE 'a%';
-- 4
SELECT NOM, TITRE
FROM EMPLOYE
WHERE NOM LIKE 'A%';
-- 5
SELECT NOM, UNITCOD
FROM EMPLOYE
WHERE SALAIRE > 250000;
-- 6
SELECT NOM, UNITCOD, TITRE, DATNAISS
FROM EMPLOYE
ORDER BY UNITCOD, DATNAISS DESC;
-- 7
SELECT E.NOM, E.UNITCOD
FROM EMPLOYE , QUALIF
JOIN QUALIF Q ON Q.CODQUAL = E.QUALIFPR -- where qualifpr = codqual
WHERE Q.QUALIBEL = 'secrétaire';
-- 8
SELECT E1.NOM, E1.UNITCOD, E1.DATNAISS,
       R.NOM AS RESPONSABLE, R.DATNAISS AS DATRESPO
FROM EMPLOYE E1
JOIN UNITE U ON U.UNITCOD = '2000'
JOIN EMPLOYE R ON R.EMPCOD = U.UMERE
WHERE E1.DATNAISS < R.DATNAISS
ORDER BY E1.UNITCOD;
-- 8
select 
from employe,employe as employer
where employer.titre = "respo"
and employe.unitcod = employer.unitcod
employe.datenaiss < employer.datenaiss
order by (employe.unitcode);


-- 9
SELECT NOM, TITRE
FROM EMPLOYE
WHERE DATNAISS < (
    SELECT DATNAISS
    FROM EMPLOYE
    WHERE EMPCOD = (SELECT UMERE FROM UNITE WHERE UNITCOD='2000')
);
-- 10
SELECT UNITCOD
FROM UNITE
WHERE UMERE IS NULL;
-- 10
select unitcod 
from unite 
where unitcod
not in (select umer from unite);
-- 11
SELECT NOM
FROM EMPLOYE
WHERE UNITCOD = (
    SELECT UNITCOD FROM EMPLOYE WHERE NOM = 'LEVITT, P.S.'
);
-- 12
SELECT UNITCOD, UNITE
FROM UNITE
WHERE UMERE = (SELECT UMERE FROM UNITE WHERE UNITCOD='2130');
-- 13
SELECT NOM, DATNAISS
FROM EMPLOYE
WHERE DATNAISS < (
    SELECT MIN(DATNAISS)
    FROM EMPLOYE
    WHERE UNITCOD='2131'
);
-- 14
SELECT E.NOM
FROM EMPLOYE E
WHERE EXISTS (
    SELECT 1
    FROM POSTES P1
    JOIN POSTES P2 ON P1.CODQUAL = P2.CODQUAL AND P1.UNITCOD = P2.UNITCOD
    WHERE P2.UNITCOD = E.UNITCOD
      AND P2.CODQUAL = E.JOBCODE
      AND P1.CODQUAL = (SELECT JOBCODE FROM EMPLOYE WHERE NOM='LEVITT')
);
-- 15
SELECT EMPCOD, NOM
FROM EMPLOYE
WHERE UNITCOD='2122'
  AND JOBCODE IN (
      SELECT JOBCODE FROM EMPLOYE WHERE UNITCOD='2132'
  );
-- 16
SELECT DISTINCT E.NOM, E.QUALIFPR
FROM EMPLOYE E
WHERE E.UNITCOD='2111'
AND (
       E.QUALIFPR IN (SELECT QUALIFPR FROM EMPLOYE WHERE UNITCOD='2123')
    OR E.EMPCOD IN (
        SELECT EMPCOD FROM EMPSQUAL
        WHERE CODQUAL IN (
            SELECT CODQUAL FROM EMPSQUAL WHERE EMPCOD IN (
                SELECT EMPCOD FROM EMPLOYE WHERE UNITCOD='2123'
            )
        )
    )
);
-- 17
SELECT DISTINCT E.NOM, Q.QUALIBEL
FROM EMPLOYE E
JOIN QUALIF Q ON Q.CODQUAL = E.QUALIFPR
WHERE E.UNITCOD='2111'
AND Q.CODQUAL IN (
    SELECT QUALIFPR FROM EMPLOYE WHERE UNITCOD='2123'
);
-- 18
SELECT NOM,
       YEAR(GETDATE()) - YEAR(DATNAISS) AS AGE
FROM EMPLOYE
WHERE UNITCOD='2111'
ORDER BY NOM;
-- 19
SELECT NOM,
       CONCAT(YEAR(GETDATE()) - YEAR(DATNAISS), ' ans') AS AGE
FROM EMPLOYE
WHERE UNITCOD='2111'
ORDER BY NOM;
-- 20
SELECT AVG(SALAIRE) AS salaire_moyen
FROM EMPLOYE;
-- 21
SELECT U.UNITCOD, U.UNITE, COUNT(E.EMPCOD) AS NB_EMP
FROM UNITE U
LEFT JOIN EMPLOYE E ON U.UNITCOD = E.UNITCOD
GROUP BY U.UNITCOD, U.UNITE;
-- 22
SELECT TOP 1 JOBCODE, Q.QUALIBEL,
       AVG(SALAIRE) AS MOYENNE
FROM EMPLOYE E
JOIN QUALIF Q ON Q.CODQUAL = E.JOBCODE
GROUP BY JOBCODE, Q.QUALIBEL
ORDER BY MOYENNE ASC;

